---
- name: external repository / popular software programs
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    # ----------------------------------
    - git
    - unzip
    - vim
    - zip