---
- name: build environment (nokogiri)
  yum: name={{ item }} state=present
  with_items:
    - libxml2
    - libxslt-devel
- name: build environment (therubyracer)
  yum: name=gcc-c++ state=present